### ISSUE TITLE
Replace the xmlrpcserver with a rest interface

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloud-scheduler#412]
Instead of using the xmlrpc server replace it with a web.py rest interface, which should also make securing the admin client easier.

**Comment by darrylring** [comment]
After a review of the `admin_server.py`, `info_server.py` servers and `cloud_admin`, and `cloud_status` clients, I propose the following URL schema. I've indicated the HTTP method, URLs, and the XML-RPC functions that map to each request.

**admin_server**

```http
PUT		/?log_level=LOG_LEVEL
			change_log_level
POST	/?action=reconfig|quick_shutdown
			cloud_resources_reconfig
			perform_quick_shutdown
PUT		/clouds/CLOUD?action=(enable|disable)
			enable_cloud
			disable_cloud
PUT		/clouds/CLOUD?allocations=NUMBER
			adjust_cloud_allocation
DELETE	/clouds/CLOUD/vms
			delete_all_vm_entry_cloud
PUT		/clouds/CLOUD/vms?action=shutdown[&count=all|NUMBER]
			shutdown_cluster_count
			shutdown_cluster_all
POST	/clouds/CLOUD/vms?action=force_retire[&count=all|NUMBER]
			force_retire_count_vm
			force_retire_all_vm
DELETE	/clouds/CLOUD/vms/VMID
			delete_vm_entry
PUT		/clouds/CLOUD/vms/VMID?action=(reset_override_state|shutdown)
			reset_override_state
			shutdown_vm
POST	/clouds/CLOUD/vms/VMID?action=force_retire
			force_retire_vm
POST	/users/USER?refresh=(job_proxy|vm_proxy)
			refresh_job_proxy_user
			refresh_vm_proxy_user
GET		/cloud_aliases
			list_cloud_alias
PUT		/cloud_aliases
			cloud_alias_reload
GET		/user_limits
			list_user_limits
PUT		/user_limits
			user_limit_reload
```

**info_server**

```http
GET		/
			get_version
GET		/cloud
			get_cloud_resources
GET		/cloud/config
			get_cloud_config_values
GET		/cloud.json
			get_json_resource
GET		/clusters
			get_cluster_resources
GET		/clusters/CLUSTER
			get_cluster_info
GET		/clusters/CLUSTER.json
			get_json_cluster
GET		/clusters/CLUSTER/vms
			get_vm_stats
			get_total_vms_cloud
GET		/clusters/CLUSTER/vms/VMID
			get_vm_info
GET		/clusters/CLUSTER/vms/VMID.json
			get_json_vm
GET		/jobs?state=(new|sched|high|idle|running|complete|held)
			get_newjobs
			get_schedjobs
			get_highjobs
			get_idlejobs
			get_runningjobs
			get_completejobs
			get_heldjobs
GET		/jobs/JOBID
			get_job
GET		/jobs/JOBID.json
			get_json_job
GET		/vms[?metric=total|missing|startup_time|job_run_times]
			get_cluster_vm_resources
			get_total_vms
			get_missing_vm_list
			get_vm_startup_time
			get_vm_job_run_times
GET		/job_pools.json
			get_json_jobpool
GET		/developer_info
			get_developer_information
GET		/ips
			get_ips_munin
GET		/diff_types
			get_diff_types
GET		/failures[?reasons]
			get_image_failures
			get_job_failure_reasons
GET		/shared_objs
			check_shared_objs
GET		/thread_heart_beats
			get_thread_heart_beats
```

I've tried to follow the REST "standard" where `GET` requests are safe, `PUT` requests are unsafe but idempotent, and `POST` and `DELETE` are neither.

On the server-side, web.py will provide the HTTP server and request dispatcher. On the client-side, [requests](http://docs.python-requests.org/en/latest/) would be ideal at the possible cost of an additional dependency. The `urllib2` module is the obvious alternative, though its API is significantly more complicated and would require quite a bit of additional code. Funnily enough, the documentation for `urllib2` recommends using `requests` instead.

As a next step I can create an isolated version of the admin and info servers and clients that make use of the REST API but don't need any real configuration or data.

**Comment by mhpx** [comment]
Sounds good. 
Use requests and update the setup.py in your branch to reflect the requirement.

**Comment by darrylring** [comment]
I have this well underway in the `rest` branch of my repo: https://github.com/darrylring/cloud-scheduler/tree/rest.

I've updated both `cloud_admin` and `cloud_status` to implement the REST API proposed above (which I've updated) and create stub servers for testing (`rest_admin_server.py` and `rest_info_server.py`). Right now each request simply returns the name of the XML-RPC function it replaces.

There are some XML-RPC functions that aren't currently called from the clients. I've left these out of the REST API implementation for the moment, but I can easily add them. They are:
- get_job
- get_json_job
- get_json_jobpool
- check_shared_objs

I've added `web.py` and `requests` to the project's dependencies (in `setup.py` and `README.md`).

**Tasks**
- [x] ~~Add new dependencies~~
- [x] ~~Update `cloud_admin` and `cloud_status` clients to use REST API~~
- [x] ~~Create test stub servers `rest_admin_server.py` and `rest_info_server.py` for testing~~
- [ ] Update actual servers to provide REST API
- [ ] Update cloud_scheduler on development server
- [ ] Test REST clients with running VMs and jobs
- [ ] Add additional sanity and error checking

**Comment by darrylring** [comment]
Both clients and servers have been updated in the `rest` branch of my repo: https://github.com/darrylring/cloud-scheduler/tree/rest. I've done some basic testing of both with Cloud Scheduler running on my local machine. I will be adding some additional sanity and error checking.

I imagine the next step is to test it on the development server.

**Comment by darrylring** [comment]
Okay, I have my branch running on the development server, and things are looking good. I've run through each combination of commands that `cloud_status` supports and they're all working correctly (I had to fix a few issues). Next is `cloud_admin` and then trying to break both commands with bad input.

**Testing**
- [x] `cloud_status`
- [ ] `cloud_admin`
- [ ] Try to break both with bad input
